### ISSUE TITLE
FullText operator must search in all searchable document fields

### ISSUE THREAD

**Issue by adrianco48** [adrianco48/lib-search-engine-elasticsearch#11]
Thanks to @tim-bezhashvyly for the parallel with Solr internal workings on full text search!!

Looks like this is the exact case for the [`_all` Elasticsearch synonym](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/mapping-all-field.html).

**Comment by adrianco48** [comment]
Modified the title to read 'all searchable' document fields as per @tim-bezhashvyly request

**Comment by adrianco48** [comment]
Looks like selecting only searchable fields is possible using `include_in_all` option at mapping setup as per [this article](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/include-in-all.html)

**Comment by tim-bezhashvyly** [comment]
Great idea. Implemented it as a part of PR #12.

**Comment by adrianco48** [comment]
Thank you!
