### ISSUE TITLE
Facet filter transformations are not applied

### ISSUE THREAD

**Issue by tim-bezhashvyly** [adrianco48/lib-search-engine-elasticsearch#3]
Facet filter transformations are passed to `ElasticsearchAggregationsRequest` but never used in there.

**Comment by tim-bezhashvyly** [comment]
Also I assume selected filters must be passed to `ElasticsearchAggregationsRequest`.

**Comment by adrianco48** [comment]
I think I might finally get your point!

When I was doing some A/B testing on `catalogsearch` requests and added lots of filters, at some point I deselected a couple ones. This not only left me without any results but my previously selected filters and their counts also disappeared and my only way back was by browser back button.

At that time I thought that this would be an incomplete functionality in the L&P `sample-project` catalog search which unlike layered navigation it doesn't have the "SELECTED FILTERS" along with the "X" buttons for every selected filters atop.

But now I believe FacetFieldTransformationRegistry would have to be merged with selected filters.

Looking into it.

Thank you!
